# Add 'repo' label to any root file changes
Tests:
  - 'tests/*'
  - 'tests/**/*'
Features:
  - 'project/features/*'
  - 'project/features/**/*'
API:
  - 'project/api/*'
  - 'project/api/**/*'
Integration:
  - 'project/integration/*'
  - 'project/integration/**/*'
