# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  pull_request:
    branches: [ main, development ]

jobs:
  build:

    runs-on: python:3.10-slim

    steps:
    - uses: actions/checkout@v2
    - name: Prepare environment
      run: |
        python -m pip install --upgrade pip
        pip3 install pipenv
    - name: Install dependencies
      run: |
        pipenv install --system --deploy --ignore-pipfile --dev
    - name: Lint with isort
      run: |
        pipenv run isort .
    - name: Lint with flake8
      run: |
        pipenv run flake8
    - name: Test with pytest
      run: |
        python -m pytest